// <auto-generated />
namespace VisioConference.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class modelInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modelInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "202107020849349_modelInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
