// <auto-generated />
namespace VisioConference.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModifUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202107171401059_ModifUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
